if(EXISTS "/home/omar/compression-geospatial-git/build_skipexc/test_comp[1]_tests.cmake")
  include("/home/omar/compression-geospatial-git/build_skipexc/test_comp[1]_tests.cmake")
else()
  add_test(test_comp_NOT_BUILT test_comp_NOT_BUILT)
endif()
